version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Australia/Sydney
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.15
    - 6.1.16
    - 6.1.17
    - 6.1.18
    - 6.1.19
    - 6.1.20
    - 6.1.21
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.5
    - 6.2.7
    - 6.2.8
  - dependency-name: jsdom
    versions:
    - 16.4.0
    - 16.5.0
    - 16.5.1
    - 16.5.2
  - dependency-name: webpack-bundle-analyzer
    versions:
    - 4.4.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
